= About

This repository contains the `vboxconfig.sh` script fixed to properly detect
non-"Oracle Solaris 11" platforms during VirtualBox installations.

This script estimates the OS environment on the VirtualBox host and chooses
which drivers to install and register, for Solaris ("SunOS" distro) in
particular. In case of the extended Solaris family (based on the open-sourced
illumos core) the original Sun/Oracle Solaris logic does not work well, so
to cater for these systems some fixes were needed.

== Flag-files

The original script supports influence on its configuration by having the
administrator touch certain files before installation begins. This patch
extends such approach with more files to touch (e.g. if your environment
does not fit the expectations of the existing script).

Useful names (relative to the package installation root directory) include:

* `/etc/vboxinst_vboxflt` -- install NetFilter (STREAMS) networking module
(applicable for illumos)

* `/etc/vboxinst_vboxbow` -- install CrossBow networking module (for
Oracle Solaris 11 snv_159+)

* `/etc/vboxinst_vboxusb` -- force-attempt installation of the USBMonitor
module and the USB module (otherwise requires that the script detects that
your host kernel is at least Solaris 11 build 124 or Solaris 12)

== Branches

The `downloaded` branch shall contain occasional snapshots of the script
provided by the upstream VirtualBox downloadable distributions.

The `illumos-fix` is my work in progress as I develop and test the script,
as well as rebase it to newer upstream versions over time.

The `master` branch is a sort of release variant of the `illumos-fix` --
whatever seems stable enough to publish and use for everybody daring enough ;)

== License

Common license for the script itself is GPLv2 as in VirtualBox OSE.
Patch changes are released under MIT License so as to conform to contribution
requirements for the upstream Oracle VirtualBox project.

In any case, I hope these changes would be found useful and might wind up
in pre-packaged distributions, be it the original Oracle VirtualBox, or
any of the OSE builds in illumos distributions.


= Applying and using the patch to (un)install an unmodified VirtualBox package

NOTE: Thanks to "russell" from the OpenIndiana mailing list for pointing
in the right direction for this simplified procedure.

If you can stand an "unclean" install/uninstall procedure, which is quite
acceptable e.g. on a single-user desktop (as opposed to a VM server farm),
you can follow this simple procedure:

* Download this patch to your machine:
----
:; mkdir -p /var/tmp/vbox
:; cd /var/tmp/vbox
:; wget https://raw.githubusercontent.com/jimklimov/vboxconfig_sh/master/vboxconfig.sh.patch
----

* If you have on old version of VirtualBox already installed, you have to
uninstall it before upgrading. If `pkgrm SUNWvbox` fails, you may need to
patch (or replace) the `/opt/VirtualBox/vboxconfig.sh`:
----
:; ( cd /opt/VirtualBox/ && gpatch -p1 ) < vboxconfig.sh.patch
patching file vboxconfig.sh
----
Note that some "fuzz" or "offset <by a small number of> lines" messages may
be reported by `gpatch`. If they are not "FAILED", this is generally harmless.
Complete uninstallation of old version with `pkgrm SUNWvbox`.

* Install the new version according to standard procedure. Watch it fail
to configure in the end.

* Patch the newly installed `/opt/VirtualBox/vboxconfig.sh` following the
procedure above, and run it to complete the installation:
----
:; ( cd /opt/VirtualBox/ && ./vboxconfig.sh --postinstall )
----

* At this point, your update should be complete.


= Applying and using the patch to install VirtualBox from the package file

If you like package installations to be marked clean and report no errors,
you should patch the downloaded package to include the enhanced script.

NOTE: The instructions below were tested on an OpenIndiana Hipster 2015.0
installation and on an OmniOS Bloody 151015.

* Download a VirtualBox distribution for "SunOS" (x86/amd64) hosts from
http://download.virtualbox.org/virtualbox/ and unpack the archive, e.g.:
----
:; mkdir -p /var/tmp/vbox
:; cd /var/tmp/vbox
:; wget https://raw.githubusercontent.com/jimklimov/vboxconfig_sh/master/vboxconfig.sh.patch
:; wget -c http://dlc-cdn.sun.com/virtualbox/4.3.28/VirtualBox-4.3.28-100309-SunOS.tar.gz && \
   gzip -cd < "`ls -1 VirtualBox-*-SunOS.tar.gz | tail -1`" | tar xvf -

VirtualBox-4.3.28-SunOS-amd64-r100309.pkg
LICENSE
autoresponse
ReadMe.txt
----

* Unpack the package into individual files (this creates a subdirectory
named `SUNWvbox` under the target directory `./` in our example case):
----
:; yes '' | pkgtrans "`ls -1 VirtualBox-*-SunOS*pkg | tail -1`" ./
:; du -ks SUNWvbox/ ; find SUNWvbox/ | grep vboxconfig
210448  SUNWvbox/
SUNWvbox/root/opt/VirtualBox/vboxconfig.sh
----

* Apply the patch:
----
:; ( cd SUNWvbox/root/opt/VirtualBox/ && gpatch -p1 ) < vboxconfig.sh.patch
patching file vboxconfig.sh
----
Note that some "fuzz" or "offset <by a small number of> lines" messages may
be reported by `gpatch`. If they are not "FAILED", this is generally harmless.

* Fix up the SVR4 package metadata (embed new size and checksum of the
resulting file into the `pkgmap`):
----
:; CSSZ="$( /bin/cksum -B1 -s SUNWvbox/root/opt/VirtualBox/vboxconfig.sh | awk '{print $2" "$1}' )" && \
   echo "$CSSZ"
47288 14514

:; sed 's,^\(.* f .* /opt/VirtualBox/vboxconfig.sh [^ ]* [^ ]* [^ ]* \)\([^ ]* [^ ]* \)\([^ ]*\)$,\1'"$CSSZ "'\3,' \
    -i SUNWvbox/pkgmap

:; grep -i vboxconfig SUNWvbox/pkgmap
1 f none /opt/VirtualBox/vboxconfig.sh 0755 root bin 47288 14514 1431530679
----

CAUTION: The next step covers installation of the resulting patched package on
a hypervisor host. Keep in mind that this process *will* disrupt networking,
so initiate the installation only from an out-of-band connection (console)
or at least a non-disruptable session (VNC, `screen`) so that the SSH link
disconnection will not botch the installation.

* Hope that all went well above, and install the package (in case of upgrading
or retrying, remove an old one first):
----
:; cd /var/tmp/vbox && \
   if [ -d /var/sadm/pkg/SUNWvbox ] ; then yes y | pkgrm SUNWvbox ; fi && \
   yes '' | pkgadd -d . -a ./autoresponse
----

* If you want to reuse the resulting package on several hosts, you can copy
over the `SUNWvbox` subdirectory and install it in the same way as above,
or you can `pkgtrans` it back into a single file for more convenient storage,
e.g.:
----
:; pkgtrans . VirtualBox\-4.3.28\-SunOS\-amd64\-r100309-illumos.pkg SUNWvbox
Transferring <SUNWvbox> package instance
----

* After updating the host software, if you're using the PUEL-licensed extension
pack, don't forget to update it as well. A nice automation was posted on the
VirtualBox forums https://forums.virtualbox.org/viewtopic.php?f=7&t=44337 by
"Sasquatch":
----
#!/bin/bash
if version=$(VBoxManage -v) ; then
  echo $version
  var1=$(echo $version | cut -d 'r' -f 1)
  echo $var1
  var2=$(echo $version | cut -d 'r' -f 2)
  echo $var2
  file="Oracle_VM_VirtualBox_Extension_Pack-$var1-$var2.vbox-extpack"
  echo $file
  wget -c http://download.virtualbox.org/virtualbox/$var1/$file -O /tmp/$file
  sudo VBoxManage extpack uninstall "Oracle VM VirtualBox Extension Pack"
  sudo VBoxManage extpack install /tmp/$file --replace
fi
----

* Do not forget to update VirtualBox Guest Additions on the virtual machines,
this may be especially important for continued X11 guest desktop support.

= X.Org config file chooser for dual-booted VM/HW setups

I have an OI installation on a laptop alternately running as a VM or as a
"physical" OS. One of the implications is that there are different preset
X11 driver configurations relevant to different hardware. A nifty trick I
saw advised on the internet was to add an init-script that would choose
the suitable pre-made X11 config file and install it, before running GDM
or equivalent graphics engine.

This is what `S98vbox-dualboot-xorg` script is intended for. Look in the
sources for hints on configuration, and copy and tune the needed config
files as `/etc/X11/xorg.conf*` names referenced in the script variables
(as is, or renamed via its own optional simple config file).

= XSession tweaks for VirtualBox Guest Additions and non-Oracle X sessions

As OpenIndiana Hipster switched to offer MATE instead of GNOME2 recently,
I found that the Guest Additions' `VBoxClient` is not started under the new
sessions. Without much further digging about the causes, I made a config
file to force startup of those clients in any X session instead (IFF the
hardware is deemed to be a VirtualBox -- so it is friendly to dual-booters).
Just copy `0980.VBGA` to `/etc/X11/xinit/xinitrc.d/` and make sure it is
marked as executable, and it should be picked up by `/etc/gdm/Xsession`
script processing when an X11 session starts up for any user. Alternately,
reference a copy of this code from your account's `~/.xprofile` file, if
you want to limit the impact to just a few users.

Research has shown that it is not a problem to run `VBoxClient` twice or
more -- the daemon only forks and runs once (overall there's two processes
for each of the options), so it should not cause problems for GNOME2 sessions
as well.

Good luck,
Jim Klimov

''''

# Original mailing-list announcement

_slightly edited_

----
* From: Jim Klimov
* To: vbox-dev@virtualbox.org
* Date: 9 Mar 16:09 2015 
* Subj: Patch to support installation on non-Sun/Oracle Solaris hosts

Hello all,

I submit a patch which should simplify installation of modern VirtualBox
on some non-Oracle derivate distributions of Solaris which are known to
host VirtualBox just fine. Most of the patch deals with "proper" detection 
of major and minor OS version numbers on those distributions. Also there
is now a touchable filename to enforce installation of USB filters and
corresponding UNIX group accounts, as a workaround for further distros
not detected as supported by even new code.

I submit this patch under the terms of MIT license.

This was last tested with VirtualBox 4.3.24 and OpenIndiana Hipster and
OmniOS Bloody, all updated today to the most current states available.

Note this was not yet tested in practice with OpenSolaris SXCE (yes, I do
have some running), although snippets were developed that should work there.
I don't expect there are many of those installations left beside my closet,
but those are all pleased with old VBox versions for now... ain't broke,
you know ;)

Hope this helps, 
// Jim Klimov
----
